package com.rohan.spring_boot_rest;

import com.rohan.spring_boot_rest.model.JobPost;
import com.rohan.spring_boot_rest.service.JobService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class SpringBootRestApplicationTests {

	@Autowired
	private JobService service;

	@Test
	void contextLoads() {
	}

	@Test
	void testAddJobAndVerifyTechStack() {
		int testId = 169 + (int)(Math.random() * 1000); // Use a unique-ish ID for test
		String uniqueProfile = "Unique Profile " + testId;
		JobPost job = new JobPost();
		job.setPostId(testId);
		job.setPostProfile(uniqueProfile);
		job.setPostDesc("test through web");
		job.setReqExperience(6);
		job.setPostTechStack(List.of("Java", "Spring Boot"));

		service.addJob(job);

		JobPost savedJob = service.getJob(testId);

		assertNotNull(savedJob, "Job should be saved");
		assertEquals(testId, savedJob.getPostId(), "ID should be preserved");
		assertEquals(uniqueProfile, savedJob.getPostProfile());
		assertNotNull(savedJob.getPostTechStack(), "Tech stack should not be null");
		assertFalse(savedJob.getPostTechStack().isEmpty(), "Tech stack should not be empty");
		assertEquals(2, savedJob.getPostTechStack().size());
		assertTrue(savedJob.getPostTechStack().contains("Java"));
	}

	@Test
	void testAddJobAutoGeneratedId() {
		JobPost job = new JobPost();
		job.setPostProfile("test in the webDev server");
		job.setPostDesc("test in webDev server");
		job.setReqExperience(7);
		job.setPostTechStack(List.of("Java", "React"));

		service.addJob(job);

		assertNotNull(job.getPostId(), "ID should be generated");
		
		JobPost savedJob = service.getJob(job.getPostId());

		assertNotNull(savedJob);
		assertEquals(job.getPostId(), savedJob.getPostId());
		assertEquals("test in the webDev server", savedJob.getPostProfile());
		assertNotNull(savedJob.getPostTechStack());
		assertFalse(savedJob.getPostTechStack().isEmpty());
	}
}
